
set(3RD_PARTY_OPENAL "${3RD_PARTY_SOURCE_DIR}/openal-soft-1.17.2")
message("OpenAL from ${3RD_PARTY_OPENAL}")
set(3RD_PARTY_SDL2 "${3RD_PARTY_SOURCE_DIR}/SDL2-2.0.5")
message("SDL2 from ${3RD_PARTY_SDL2}")
set(3RD_PARTY_WXMSW28 "${3RD_PARTY_SOURCE_DIR}/wxMSW-2.8.12")
message("wxMSW2.8 from ${3RD_PARTY_WXMSW28}")
set(3RD_PARTY_WXWIDGETS31 "${3RD_PARTY_SOURCE_DIR}/wxWidgets-3.1.0")
message("wxWidgets3.1 from ${3RD_PARTY_WXWIDGETS31}")

set(3RD_PARTY_WXWIDGETS ${3RD_PARTY_WXWIDGETS31})
